version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app


    ports:
      - "3000:3000"
    image: t3-app
    environment:
      - DATABASE_URL=""
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=""
      - CLERK_SECRET_KEY=""
      - NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
      - NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/dashboard
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/dashboard
      - NEXT_PUBLIC_S3_ACCESS_KEY_ID=""
      - NEXT_PUBLIC_S3_SECRET_ACCESS_KEY=""
      - NEXT_PUBLIC_S3_BUCKET_NAME="clickbait-nextjs-storage" 
      - NEXT_PUBLIC_S3_REGION="ap-south-1"
      - PINECONE_ENVIRONMENT="None"
      - PINECONE_API_KEY=""
    networks:
      - my-bridge-network

networks:
  my-bridge-network:
    driver: bridge